package tools

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	skill "github.com/OctoSucker/octosucker-skill"
)

// DiscoverSkillsFromGoMod 从 go.mod 文件自动发现 skill 包
// 扫描 go.mod 中所有包含 "skill" 的依赖包
func DiscoverSkillsFromGoMod(projectRoot string) ([]string, error) {
	goModPath := filepath.Join(projectRoot, "go.mod")
	if _, err := os.Stat(goModPath); os.IsNotExist(err) {
		return nil, nil
	}

	content, err := os.ReadFile(goModPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read go.mod: %w", err)
	}

	var skillPackages []string
	lines := strings.Split(string(content), "\n")
	inRequire := false

	for _, line := range lines {
		line = strings.TrimSpace(line)

		// 检测 require 块
		if line == "require (" {
			inRequire = true
			continue
		}
		if line == ")" {
			inRequire = false
			continue
		}

		// 在 require 块中查找 skill 包
		if inRequire || strings.HasPrefix(line, "require ") {
			// 提取包路径（移除 require 关键字和版本号）
			parts := strings.Fields(line)
			for _, part := range parts {
				// 跳过 require 关键字
				if part == "require" {
					continue
				}
				// 移除版本号（@v1.0.0）
				pkgPath := strings.Split(part, "@")[0]
				// 检查是否包含 skill 关键字（约定：skill 包名包含 "skill"）
				if pkgPath != "" &&
					strings.Contains(strings.ToLower(pkgPath), "skill") &&
					!strings.Contains(pkgPath, "OctoSucker") { // 排除主项目
					skillPackages = append(skillPackages, pkgPath)
					break // 每行只取第一个包路径
				}
			}
		}
	}

	return skillPackages, nil
}

// DiscoverSkillsFromGoList 使用 go list 命令发现已安装的 skill 包
// 这个方法更可靠，因为它查询的是实际安装的包
func DiscoverSkillsFromGoList(projectRoot string) ([]string, error) {
	// 使用 go list 列出所有依赖
	cmd := exec.Command("go", "list", "-m", "all")
	cmd.Dir = projectRoot
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("failed to run go list: %w", err)
	}

	var skillPackages []string
	lines := strings.Split(string(output), "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		// 提取包路径（移除版本号）
		parts := strings.Fields(line)
		if len(parts) == 0 {
			continue
		}

		pkgPath := parts[0]
		// 检查是否包含 skill 关键字
		if strings.Contains(strings.ToLower(pkgPath), "skill") &&
			!strings.Contains(pkgPath, "OctoSucker") {
			skillPackages = append(skillPackages, pkgPath)
		}
	}

	return skillPackages, nil
}

// LoadSkillsAuto 自动发现并加载所有 skill
// 优先使用 go list，如果失败则回退到扫描 go.mod
func LoadSkillsAuto(projectRoot string, toolRegistry *skill.ToolRegistry, agentInstance AgentToolExecutor) error {
	var skillPackages []string
	var err error

	// 方法 1：使用 go list（更可靠）
	skillPackages, err = DiscoverSkillsFromGoList(projectRoot)
	if err != nil {
		// 方法 2：回退到扫描 go.mod
		skillPackages, err = DiscoverSkillsFromGoMod(projectRoot)
		if err != nil {
			return fmt.Errorf("failed to discover skills: %w", err)
		}
	}

	if len(skillPackages) == 0 {
		return nil // 没有找到 skill，不是错误
	}

	// 尝试加载每个 skill
	// 注意：由于 Go 的限制，我们无法在运行时动态 import
	// 所以需要通过代码生成或配置文件来实现
	// 这里我们生成一个临时的 import 文件，或者使用配置文件

	// 方案：生成一个 skill_imports.go 文件
	return generateSkillImports(skillPackages, projectRoot)
}

// generateSkillImportsContent 生成 skill 导入文件的内容
func generateSkillImportsContent(skillPackages []string) string {
	var imports []string
	imports = append(imports, "// Code generated by Agent. DO NOT EDIT.")
	imports = append(imports, "// This file is automatically generated when Agent discovers skill packages.")
	imports = append(imports, "// It contains blank imports for all skill packages installed via go get.")
	imports = append(imports, "//")
	imports = append(imports, "// To add a skill:")
	imports = append(imports, "//   1. Run: go get github.com/your-org/crabclaw-skill-name@latest")
	imports = append(imports, "//   2. Restart Agent (it will auto-generate this file)")
	imports = append(imports, "")
	imports = append(imports, "package main")
	imports = append(imports, "")
	imports = append(imports, "import (")

	for _, pkg := range skillPackages {
		imports = append(imports, fmt.Sprintf("\t_ %q", pkg))
	}

	imports = append(imports, ")")

	return strings.Join(imports, "\n")
}

// generateSkillImports 生成 skill 导入文件
// 这会创建一个 skill_imports.go 文件，包含所有发现的 skill 包的空白导入
func generateSkillImports(skillPackages []string, projectRoot string) error {
	if len(skillPackages) == 0 {
		return nil
	}

	content := generateSkillImportsContent(skillPackages)

	// 写入到 skill_imports.go 文件
	importFile := filepath.Join(projectRoot, "skill_imports.go")
	if err := os.WriteFile(importFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write skill_imports.go: %w", err)
	}

	return nil
}

// LoadSkillsFromConfig 从配置文件加载 skill 列表
// 配置文件格式：JSON 数组，包含 skill 包路径列表
func LoadSkillsFromConfig(configPath string) ([]string, error) {
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return nil, nil
	}

	content, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read skill config: %w", err)
	}

	var skillPackages []string
	if err := json.Unmarshal(content, &skillPackages); err != nil {
		return nil, fmt.Errorf("failed to parse skill config: %w", err)
	}

	return skillPackages, nil
}

// SaveSkillsToConfig 保存 skill 列表到配置文件
func SaveSkillsToConfig(skillPackages []string, configPath string) error {
	content, err := json.MarshalIndent(skillPackages, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal skill config: %w", err)
	}

	return os.WriteFile(configPath, content, 0644)
}
